// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"license-plates-api/plate"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InitPlateAPI(db *gorm.DB) plate.PlateAPI {
	plateRepository := plate.ProvidePlateRepostiory(db)
	plateService := plate.ProvidePlateService(plateRepository)
	plateAPI := plate.ProvidePlateAPI(plateService)
	return plateAPI
}
